// Generated by gencpp from file custom_msgs/InverseKinematicsForPose.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICSFORPOSE_H
#define CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICSFORPOSE_H

#include <ros/service_traits.h>


#include <custom_msgs/InverseKinematicsForPoseRequest.h>
#include <custom_msgs/InverseKinematicsForPoseResponse.h>


namespace custom_msgs
{

struct InverseKinematicsForPose
{

typedef InverseKinematicsForPoseRequest Request;
typedef InverseKinematicsForPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseKinematicsForPose
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::InverseKinematicsForPose > {
  static const char* value()
  {
    return "64e345b87f38099c3cc1cc7c03cb146a";
  }

  static const char* value(const ::custom_msgs::InverseKinematicsForPose&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::InverseKinematicsForPose > {
  static const char* value()
  {
    return "custom_msgs/InverseKinematicsForPose";
  }

  static const char* value(const ::custom_msgs::InverseKinematicsForPose&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsForPoseRequest> should match
// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsForPose >
template<>
struct MD5Sum< ::custom_msgs::InverseKinematicsForPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::InverseKinematicsForPose >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsForPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::InverseKinematicsForPoseRequest> should match
// service_traits::DataType< ::custom_msgs::InverseKinematicsForPose >
template<>
struct DataType< ::custom_msgs::InverseKinematicsForPoseRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::InverseKinematicsForPose >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsForPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsForPoseResponse> should match
// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsForPose >
template<>
struct MD5Sum< ::custom_msgs::InverseKinematicsForPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::InverseKinematicsForPose >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsForPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::InverseKinematicsForPoseResponse> should match
// service_traits::DataType< ::custom_msgs::InverseKinematicsForPose >
template<>
struct DataType< ::custom_msgs::InverseKinematicsForPoseResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::InverseKinematicsForPose >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsForPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICSFORPOSE_H
