(cl:defpackage custom_msgs-srv
  (:use )
  (:export
   "INVERSEKINEMATICSFORPOSE"
   "<INVERSEKINEMATICSFORPOSE-REQUEST>"
   "INVERSEKINEMATICSFORPOSE-REQUEST"
   "<INVERSEKINEMATICSFORPOSE-RESPONSE>"
   "INVERSEKINEMATICSFORPOSE-RESPONSE"
   "SMOOTHPATH"
   "<SMOOTHPATH-REQUEST>"
   "SMOOTHPATH-REQUEST"
   "<SMOOTHPATH-RESPONSE>"
   "SMOOTHPATH-RESPONSE"
  ))

